.PHONY: all clean

all: front back

allt: frontt backt

front:
	@cd src/frontend && make

frontt:
	@cd src/frontend && make splct

back:
	@cd src/backend && make

backt:
	@cd src/backend && make optt && make tcgt

clean:
	@cd src/backend && make clean
	@cd src/frontend && make clean
